### PR TITLE
Support > 0.9 properly

### PR DESCRIPTION
**Pull request by flanamacca**
Fooked up the 0.9 detection... needs to be number not string comparitor

### CODE REVIEW

**Comment by robertpitt** [comment]
thi's doesn't work for 1.* versions of Meteor.

**Comment by flanamacca** [comment]
Hey Robert,

Are you getting any errors ? Have an example of your deploy.json file
settings where you specify the meteor version>?

Let me know and i can have a look.

As a FYI just this morning i deployed Meteor 1.X apps this morning (inc 1.1
which was just released)

On Thu, Apr 2, 2015 at 1:33 AM, Robert Pitt <notifications@github.com>
wrote:

> thi's doesn't work for 1.* versions of Meteor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chriswessels/meteor-deployment-manager/pull/3#issuecomment-88506830>
> .
>



-- 
Regards

Roland Flanagan

**Comment by robertpitt** [comment]
Yea I figured out the issue, it was due to the fact that I installed via the NPM Package repo (`npm install meteor-deployment-manager`) which hasn't been updated since last year and doesn't have the fix in.

Installing via `npm install https://github.com/chriswessels/meteor-deployment-manager/archive/master.tar.gz` works fine.

Can you schedule an update for the npm repository please.

**Comment by chriswessels** [comment]
Will do @robertpitt!

**Pull request merged**
